wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1673608276.534614
    t:
      1:
      - 1
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 49
      - 55
      - 63
      3:
      - 19
      - 23
      4: 3.9.13
      5: 0.13.7
      8:
      - 5
batch_size:
  desc: null
  value: 8
epochs:
  desc: null
  value: 5
lr:
  desc: null
  value: 0.001
model_arch:
  desc: null
  value: resnet18
optimizer_select:
  desc: null
  value: Adam
